title: "Ben Lovley"
description: "Showcasing tech, talks, toys, and tinkering"
url: "https://benbigbeard.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Ben Lovley"
  avatar: "/assets/images/me_headshot.jpeg"  
  bio: "Technologist | Public Speaker"
  location: "United Kingdom"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ben-lovley/?originalSubdomain=uk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/benbigbeard"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/benbigbeard/"

collections:
  pages:
    output: true
    permalink: /:name/
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main_page"
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"
      toc: true
  - scope:
      path: ""
      type: pages
    values:
      author_profile: false
  - scope:
      path: ""
      type: pages
    values:
      permalink: /
      author_profile: true

