title: "Ben BigBeard"
description: "Showcasing tech, talks, toys, and tinkering"
url: "https://benbigbeard.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Ben Lovley"
  avatar: "/assets/images/ben.jpg"  # Add this later
  bio: "Technologist | Public Speaker | Builder of Weird and Wonderful Things"

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
