title: "Ben Lovley"
description: "Showcasing tech, talks, toys, and tinkering"
url: "https://benbigbeard.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

author:
  name: "Ben Lovley"
  avatar: "/assets/images/me_headshot.jpeg"  
  bio: "Technologist | Public Speaker"

collections:
  pages:
    output: true
    permalink: /:name/
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      sidebar:
        nav: "docs"
      toc: true
