name: Add Blog Post from iOS Shortcut

on:
  repository_dispatch:
    types: [new_blog_post]

jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate post filename
        id: vars
        run: |
          slug=$(echo "${{ github.event.client_payload.title }}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
          echo "slug=$slug" >> $GITHUB_OUTPUT
          echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

      - name: Create markdown file
        run: |
          FILE="_posts/${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.slug }}.md"
          echo "---" > $FILE
          echo "title: \"${{ github.event.client_payload.title }}\"" >> $FILE
          echo "date: $(date --iso-8601=seconds)" >> $FILE
          echo "layout: single" >> $FILE
          echo "---" >> $FILE
          echo "" >> $FILE
          echo "${{ github.event.client_payload.content }}" >> $FILE

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add _posts/
          git commit -m "Add post: ${{ github.event.client_payload.title }}"
          git push

